#!/bin/sh
mvn clean package && docker build -t shubhamdockerhub/egClients .
docker rm -f egClients 2>/dev/null || true && docker run -it --name egClients -p 8080:8080 -p 4848:4848 -p 8181:8181 --name egClients shubhamdockerhub/egClients
