#!/bin/sh
mvn clean package && docker build -t shubhamdockerhub/crResources .
docker rm -f crResources 2>/dev/null || true && docker run -it --name crResources -p 8080:8080 -p 4848:4848 -p 8181:8181 --name crResources shubhamdockerhub/crResources
