#!/bin/sh
#deploy="false"
deploy="true"

image=crResources
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t shubhamdockerhub/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push shubhamdockerhub/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag shubhamdockerhub/${image}:1.0-SNAPSHOT shubhamdockerhub/${image}:latest
        docker push shubhamdockerhub/${image}:latest
    fi
fi