#!/bin/sh
mvn clean package && docker build -t shubhamdockerhub/crClient .
docker rm -f crClient 2>/dev/null || true && docker run -it --name crClient -p 8080:8080 -p 4848:4848 -p 8181:8181 --name crClient shubhamdockerhub/crClient
