#!/bin/sh
#deploy="false"
deploy="true"

image=jwtFilter_MP
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t vrushabh40/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push vrushabh40/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag vrushabh40/${image}:1.0-SNAPSHOT vrushabh40/${image}:latest
        docker push vrushabh40/${image}:latest
    fi
fi